l=[10,20,30,40,'python']

l.append('java')
print(l)
l.append([2,4,6,88,10])
print(l)
l.extend(['php','java'])
print(l)
l.extend('python')
print(l)
l.extend('p')
print(l)
l.insert(0,'java') #syntax (index-position,element)
print(l)
l.insert(0,[2,3,4,5,6])
print(l)
l.pop()
print(l)
l.remove(30)
print(l)
print(l.index(10))
